#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://database-1.ckymfzb0ajik.us-east-1.rds.amazonaws.com:3306/skkumi?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: admin
#    password: qwer1234
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/skkumi
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



